//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Practico___MARDOM___Gestion_de_Articulos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulos()
        {
            this.Articulo_stock = new HashSet<Articulo_stock>();
            this.Detalle_Entrada_Almacen = new HashSet<Detalle_Entrada_Almacen>();
            this.Detalle_Salida_Almacen = new HashSet<Detalle_Salida_Almacen>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Referencia { get; set; }
        public string Codigo_Barra { get; set; }
        public bool Expira { get; set; }
        public double Precio_1 { get; set; }
        public Nullable<double> Precio_2 { get; set; }
        public Nullable<double> Precio_3 { get; set; }
        public int Tipo_Articulo_Id { get; set; }
        public bool Activo { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo_stock> Articulo_stock { get; set; }
        public virtual Tipo_Articulo Tipo_Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Entrada_Almacen> Detalle_Entrada_Almacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Salida_Almacen> Detalle_Salida_Almacen { get; set; }
    }
}
