//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Practico___MARDOM___Gestion_de_Articulos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Entrada_Almacen
    {
        public int Id { get; set; }
        public int Articulo_id { get; set; }
        public int Cantidad { get; set; }
        public double Precio { get; set; }
        public System.DateTime fecha { get; set; }
        public int entrada_id { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Entrada_Almacen Entrada_Almacen { get; set; }
    }
}
