//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Practico___MARDOM___Gestion_de_Articulos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida_Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salida_Almacen()
        {
            this.Detalle_Salida_Almacen = new HashSet<Detalle_Salida_Almacen>();
        }
    
        public int Id { get; set; }
        public int Almacen_Id { get; set; }
        public System.DateTime Fecha_crea { get; set; }
        public Nullable<System.DateTime> Fecha_modifica { get; set; }
        public string Comentarios { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Salida_Almacen> Detalle_Salida_Almacen { get; set; }
    }
}
