//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Practico___MARDOM___Gestion_de_Articulos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valmacen
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Tipo_Almacen { get; set; }
        public bool Activo { get; set; }
    }
}
