//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Practico___MARDOM___Gestion_de_Articulos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEntrada_Almacen
    {
        public int Id { get; set; }
        public string Almacen { get; set; }
        public Nullable<System.DateTime> Fecha_Entrada { get; set; }
        public Nullable<double> Monto_Entrada { get; set; }
    }
}
